"""Add SubmissionAnswer table

Revision ID: 5c66cd926c8e
Revises: bd3d51f9841e
Create Date: 2025-06-30 11:56:50.781210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c66cd926c8e'
down_revision: Union[str, None] = 'bd3d51f9841e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissionanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['checklistitem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submissionanswer_checklist', 'submissionanswer', ['checklist_id'], unique=False)
    op.create_index('idx_submissionanswer_question', 'submissionanswer', ['question_id'], unique=False)
    op.create_index('idx_submissionanswer_user', 'submissionanswer', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_submissionanswer_user', table_name='submissionanswer')
    op.drop_index('idx_submissionanswer_question', table_name='submissionanswer')
    op.drop_index('idx_submissionanswer_checklist', table_name='submissionanswer')
    op.drop_table('submissionanswer')
    # ### end Alembic commands ###
