"""Add Notification table with indexes

Revision ID: 8cba291295eb
Revises: 5c66cd926c8e
Create Date: 2025-06-30 12:50:29.956571

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cba291295eb"
down_revision: Union[str, None] = "5c66cd926c8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notification_created_at", "notification", ["created_at"], unique=False
    )
    op.create_index("idx_notification_read", "notification", ["read"], unique=False)
    op.create_index("idx_notification_type", "notification", ["type"], unique=False)
    op.create_index("idx_notification_user", "notification", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_notification_user", table_name="notification")
    op.drop_index("idx_notification_type", table_name="notification")
    op.drop_index("idx_notification_read", table_name="notification")
    op.drop_index("idx_notification_created_at", table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
