"""Initial migration with all models

Revision ID: bd3d51f9841e
Revises:
Create Date: 2025-06-26 15:16:26.355550

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd3d51f9841e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fileupload",
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fileupload", "status")
    # ### end Alembic commands ###
